CREATE TABLE `waiter` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `WAITER_NAME` varchar(120) DEFAULT NULL,
  `WAITER_MOBILE` varchar(120) DEFAULT NULL,
  `WAITER_ADDRESS` varchar(120) DEFAULT NULL,  
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8